steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/6uss/go-pipeline"]
    env: ["PROJECT_ROOT=github.com/6uss/go-pipeline"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/swe-ci-cd/go-pipeline:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/swe-ci-cd/go-pipeline:$REVISION_ID"